# Generated by Django 4.2.5 on 2023-09-21 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessesProductsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.TextField(max_length=100)),
                ('link_to_video', models.TextField(max_length=300)),
                ('video_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100)),
                ('access_product', models.ManyToManyField(through='app_training.AccessesProductsUsers', to='app_training.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_training.productowner'),
        ),
        migrations.CreateModel(
            name='LessonViewingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_time', models.IntegerField(default=0)),
                ('status', models.TextField(default='Not viewed')),
                ('id_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_training.lesson')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_training.user')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='belongs_to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_training.product'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewing_user',
            field=models.ManyToManyField(through='app_training.LessonViewingTime', to='app_training.user'),
        ),
        migrations.AddField(
            model_name='accessesproductsusers',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_training.product'),
        ),
        migrations.AddField(
            model_name='accessesproductsusers',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_training.user'),
        ),
    ]
